name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter config --enable-linux-desktop
    - run: flutter test --coverage
    - uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}

  run:
    runs-on: ubuntu-20.04
    container:
      image: dart:stable
    steps:
    - uses: actions/checkout@v3
    - run: dart pub get
    - run: dart test
